{
 "title": "NGINX DASH",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "nginx_connections_waiting" }
   ]
  },
  {
   "title": "CONNECTIONS ACCEPTED",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "nginx_up" },
    { "expr": "nginx_connections_accepted" },
    {}
   ]
  },
  {
   "title": "HTTP Requests total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "nginx_http_requests_total" }
   ]
  },
  {
   "title": "CONNECTIONS ACTIVE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "nginx_connections_active" }
   ]
  }
 ]
}