apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
spec:
  selector:
    matchLabels:
      env: dev
      dc: IN
  template: 
    metadata: 
      labels:
        env: dev
        dc: IN
    spec:
      containers:
      - name: grafana-con
        image: monitoringartist/grafana-xxl:latest
        env:          
          - name: "GF_SECURITY_ADMIN_USER"
            value: "admin"
          - name: "GF_SECURITY_ADMIN_PASSWORD"
            value: "password"
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: mypvc
          mountPath: /var/lib/grafana/
        - name: config
          mountPath: "/etc/grafana/provisioning/datasources/datasources.yaml"
          subPath: datasources.yaml
        - name: config
          mountPath: "/etc/grafana/grafana.ini"
          subPath: grafana.ini     
        - name: config
          mountPath: "/etc/grafana/provisioning/dashboards/dashboardproviders.yaml"
          subPath: dashboardproviders.yaml 
        - name: dash
          mountPath: "/etc/grafana/provisioning/dashboards/nginxmonitor-dashboard.json"
          subPath: nginxmonitor-dashboard.json
      volumes:
      - name: mypvc
        persistentVolumeClaim:
          claimName: grafana-pvc
      #- name: graf-cm
        #configMap:
          #name: prometheus-datasource-cm
      - name: config
        configMap:
          name: grafana
      - name: dash
        configMap:
          name: nginxmonitor-dashboard
