
name: CI
on:
  pull_request:
    branches: [ main ]
  push:
    paths:
      - ci/**
      - .github/workflows/**
      - action.yml
  workflow_dispatch:
jobs:
  helm:
    name: Helm
    runs-on: ubuntu-20.04
    steps:
      - name: ugh
        run: ls -l
        working-directory: ./
      - name: Lint chart
        run: helm lint
        working-directory: ./
